alexandre-falcao/sinatrent

Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20221121183816_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
Add the html, configs and devise model.
=> Add devise configs

Gemfile.lock, app/controllers/instruments_controller.rb, app/models/instrument.rb, app/views/instruments/index.html.erb, app/views/instruments/new.html.erb, config/routes.rb, db/migrate/20221121191804_create_instruments.rb, db/migrate/20221121203312_add_default_values_to_status.rb, db/migrate/20221121210117_rename_column_type.rb, db/schema.rb, test/controllers/offers_controller_test.rb, test/models/instrument_test.rb
=> Instrument model

app/views/instruments/_form.html.erb, app/views/instruments/new.html.erb
change the form to simple form
=> change to simple form

app/controllers/instruments_controller.rb
i have changed the strong params for the create method in restaurant controller
=> updating the create method for restaurant controller

app/controllers/application_controller.rb, app/views/devise/registrations/new.html.erb, app/views/instruments/index.html.erb, db/schema.rb
adding columns firs_name and last_name to user table
=> adding columns firs_name and last_name to user table

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/instruments_controller.rb, app/policies/application_policy.rb, app/policies/instrument_policy.rb, app/views/devise/registrations/new.html.erb, app/views/instruments/index.html.erb, app/views/instruments/show.html.erb, config/routes.rb, db/schema.rb, test/policies/instrument_policy_test.rb
Add authorization to the models that we have!
=> add authorization

app/policies/instrument_policy.rb
Remove some unnecessary methods
=> remove unnecessary methods

app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, db/migrate/20221123141433_add_columns_to_users.rb, db/schema.rb
- I created a migration to add these columns in the users table.
- I added new fields in Devise’s sign up and account update forms.
- I updated the application controller
=> first and last name added to users table

app/controllers/instruments_controller.rb
i changed the strong params in the instruments controller
=> changed the strong params in the instruments controller

Gemfile, Gemfile.lock, app/controllers/instruments_controller.rb, app/models/instrument.rb, app/views/instruments/_form.html.erb, app/views/instruments/index.html.erb, app/views/instruments/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20221123144918_create_active_storage_tables.active_storage.rb, db/schema.rb
Add validations to instruments model and create image upload method.
=> Image upload

app/assets/stylesheets/components/_index.scss
=> fix the grid

app/views/instruments/_form.html.erb, app/views/instruments/show.html.erb
=> add iamge lable to form

app/controllers/bookings_controller.rb, app/models/booking.rb, app/models/instrument.rb, app/policies/booking_policy.rb, app/views/bookings/new.html.erb, config/routes.rb, db/migrate/20221124164356_create_bookings.rb, db/migrate/20221124170607_change_status_type.rb, db/schema.rb, test/controllers/bookings_controller_test.rb, test/models/booking_test.rb, test/policies/booking_policy_test.rb
- I created the booking model
- I created the bookings controller w/ the methods new and created
- I added authorization to bookings
- I created a new column 'available' to instruments table
=> booking model created

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_form_login.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/instruments/_form.html.erb, app/views/instruments/new.html.erb, app/views/shared/_button.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb, config/initializers/simple_form.rb, config/initializers/simple_form_bootstrap.rb
=> changes on the footer

app/controllers/bookings_controller.rb, config/routes.rb
=> Bookig logic

app/controllers/instruments_controller.rb, app/models/instrument.rb, app/policies/instrument_policy.rb, app/views/instruments/show.html.erb, config/routes.rb
implement the authorization logic to destroy an instrument
=> add authorization to destroy an instrument

app/controllers/bookings_controller.rb, app/models/booking.rb, db/migrate/20221125145028_change_date_in_bookings.rb, db/schema.rb
=> add booking logic

app/models/booking.rb
i improved the booking logic and added a validation to the user's date input
=> improve booking logic

app/views/bookings/new.html.erb, app/views/instruments/new.html.erb
front end for the booking form
=> booking form

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/views/instruments/index.html.erb, app/views/instruments/new.html.erb, app/views/instruments/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb, app/views/shared/_navbar.html.erb
=> frontend fix
